### ISSUE TITLE
1.1.7, 2.x database, search not functional

### ISSUE THREAD

**Issue by ageru** [jobe-m/ownkeepass#107]
## Steps to reproduce
1. Create a Keepass 2 database in KP2 on Windows. Protect it with a password and keyfile. Create groups and create all your entries in groups. Don't leave any entry in the root.
2. Transfer database and keyfile to Jolla phone
3. Open database with ownkeepass
4. Start typing the name or username of one of your entries in the search field 

## Actual result
No entries can be found

## Expected results
Entries should be shortlisted

## PS
Thanks for the awesome app and for supporting 2.x databases :grinning:

**Comment by jobe-m** [comment]
Searching in Keepass 2 databases is currently not yet supported, ie. it is not yet implemented.
What I am puzzled about is that the search field obviously does not disappear in your case.
I cannot reproduce that the search field stays visible when opening a Keepass 2 database. You should see the search field disappearing shortly after opening a Keepass 2 database.

**Comment by ageru** [comment]
From what I can see, the availability of the Search bar is a bit erratic. It would always show up if the option "Focus search bar" is activated in the settings. When that option is deactivated, sometimes it shows up, sometimes it doesn't, sometimes it shows up and disappears immediately when opening a group or going back to root. I'll look for a pattern.

By the way, I'm running Sailfish 1.1.6.27.

**Comment by jobe-m** [comment]
Hmm, I am running SFOS 1.1.7.27. So the error might be related to it but I cannot believe that ;)
Anyway, I think I will just implement searching for Keepass 2 databases soon. Just need to get some free time :)
Thanks for reporting this anyway.

**Comment by ageru** [comment]
Fixed for me in 1.1.8-1. Thank you!
