### ISSUE TITLE
[REQ] As an user, I want to see the password in another font to be able to distinguish similar symbols

### ISSUE THREAD

**Issue by w32blaster** [jobe-m/ownkeepass#109]
# Intro
Sometimes I can't just copy-paste the password from my ownKeepas, but I need to type it manually. For example, when I use public/shared computer (for example, at work) that doesn't have KeepassX installed. In this case I usually open ownKeepass on my Jolla, find appropriate account and type the password manually, looking at the smartphone screen, symbol by symbol.

# The problem
There are some symbols that are pretty hard to distinguish. For example O (capital "o") and 0 ("zero"). Or l (small "L"), | (bar symbol) and 1 (one). They look pretty similar.

![Demo password on OwnKeepass on Jolla phone](https://cloud.githubusercontent.com/assets/6038179/10663897/07e82a10-78b7-11e5-89a2-de3369d3b811.jpg)

# Suggested solution
When I open an account in ownKeepass and click the "eye" icon to show my password, as an user I would like to see shown password in different monospace font. For example, rather than to use system font:

> ?WrBe9[!L$[3Oi_w:a0kwT/Ew

it would be great to see it like that:

    ?WrBe9[!L$[3Oi_w:a0kwT/Ew

(GitHub uses "Liberation Mono" font in this case). Note, that in the above example symbols "zero" and "capital O" are displayed differently.

**Comment by jobe-m** [comment]
yes, I agree that is a good suggestion. I will implement it in one of the next releases. Thanks for reporting.

**Comment by w32blaster** [comment]
Thank you very much for your work! The OwnKeepas is really useful and handy applicaiton! :+1:
