### ISSUE TITLE
New Database Doesn't Open

### ISSUE THREAD

**Issue by r0kk3rz** [jobe-m/ownkeepass#110]
version 1.1.11 installed on sfos 2.0.0.10, freshly installed from harbour with no keepass database on device.

Create database from pulley menu, fill out form and submit, errors with 'internal key error'. Database cannot be opened with same error.

Also, it is unclear what you need to do on the initial screen, it has a field for entering a master password for a new database but there doesnt appear to be any buttons or indication on what to do next.

**Comment by jobe-m** [comment]
Thanks for reporting.
I will check the "internal key error" problem. Have you used a key file with the new database?

Regarding the second issue: You are right. I will put more descriptive text on the main page when the app is opened the first time resp. if no database yet exists or was created.

**Comment by r0kk3rz** [comment]
No key file was created.

I have also tried creating a database with KeepassX on windows, and that doesn't load either with a hash mismatch error.

**Comment by jobe-m** [comment]
Oh, what a stupid bug... I just realized while testing and reproducing that opening a database with touching "Open" at the top right of the dialog does not work. If touching the "Return" Key of the on screen keyboard the database opens (after typing the master password). I will fix it shortly with the next release.

Please retry to see if this is also the case with your issue.

**Comment by r0kk3rz** [comment]
Yep pressing the enter on the VKB works for me, but not the dialog accept. Sounds like you're onto it.
