### ISSUE TITLE
Wrong password bug?

### ISSUE THREAD

**Issue by mikmatra** [jobe-m/ownkeepass#111]
After update to 1.1.11 (Sailfish OS 2.0.0.10), I can not open a database created with desktop (Win 7) KeePass version 2.30. It shows an error message: 
"Wrong password. Either your master password is wrong or the database file is corrupt. Please try again".

**Comment by jobe-m** [comment]
Thanks for reporting the issue. I will check it.

**Comment by jobe-m** [comment]
Oh, what a stupid bug... I just realized while testing and reproducing that opening a database with touching "Open" at the top right of the dialog does not work. If touching the "Return" Key of the on screen keyboard the database opens. I will fix it shortly with the next release.

Please retry to see if this is also the case with your issue.

**Comment by jobe-m** [comment]
Release 1.1.12 with bugfix will be available shortly.
