### ISSUE TITLE
Support of KDBX4 file format

### ISSUE THREAD

**Issue by a-dekker** [jobe-m/ownkeepass#18]
As of early 2017, keepass supports this new KDBX file format. Especially the password hash Argon2 gets positive feedback.
Is support of this on the roadmap? As ownkeepass does not support it, I cannot activate it on my desktop if I want to be able to sync easily.

**Comment by jobe-m** [comment]
We need to wait until KeepassX supports this file format. If I do not want to implement it by myself for what I have no time left :-/

**Comment by a-dekker** [comment]
Hmm, could KeePassXC, the community fork of KeePassX, not be used?

**Comment by jobe-m** [comment]
I would need to check how easy or difficult it would be to migrate the database code to KeepassXC. If they did not change much at the database access level it would be possible.

**Comment by a-dekker** [comment]
In the latest KeepassXC (2.4.0) you are now forced to leave the almost deprecated KDBX 3.1 in favor of KDBX 4.0: https://github.com/keepassxreboot/keepassxc/issues/2839

As I use KeepassXC in a lot of places it will become hard to keep using OwnKeepass. Please don't make this yet another abandoned Sailfish app!

**Comment by Termitebug** [comment]
I agree with a-dekker. As a my my cross-platform usage case with ownKeepass, KeepassX is only option for this app becase it's GUI works flawlessly with Linux. 

However, KeepassX is outdated with some of it's bugs still present.

**Comment by jobe-m** [comment]
I see and understand your request for ownKeepass.
In principle is should not be so difficult to change the database code. I re-use for Keepass 2 support the database code from KeepassX. So it might be straight forward to just exchange the git sub-module at `ownkeepass/common/src/keepassPlugin/keepass2_database/keepassx` with a recent version of keepassxc.

The most work would be to get it compiling without much or any changes in the keepassxc code. As any change would make maintenance and updating the database code a nightmare...
I cannot promise anything, but that is the way to go. I will try to find some time to start looking into it. But first I need to sort out some private tasks and duties...

**Comment by a-dekker** [comment]
I had the intention to give it a try a while back, but when I could not even compile it with the current KeepassX codebase (salsa20 files mentioned in keepass2_database.pri are no longer there for example) I soon gave up with my limited C knowledge.

**Comment by V-Z** [comment]
As KeePassXS is now IMHO the best KeePass version, and as it now basically forces user to use KDBX4 format, I can't use ownKeePass at all... :-( Otherwise it's perfect application, so support for KDBX4 would be great.

**Comment by rbns** [comment]
quick note, just because i've had this problem too:

you can save the database as kdbx 3.1, but you have to remove the properties ("properties" are new in kdbx 4) set by the browser plugin manually, otherwise saving in the old format _silently_ fails. properties are stored for the database and entries, so removing them is a dull task..

after removing them i could set the key derivation function to "AES-KDF (KDBX 3.1)" in the database settings in keepassxc (check the advanced settings checkbox). this file can then be loaded by ownkeepass. don't forget to disable the browser extension so these entries don't get re-added ;)

https://github.com/keepassxreboot/keepassxc/issues/2693

**Comment by a-dekker** [comment]
A response exactly one year after opening the issue ;)
It keeps jumping back to KDBX 4 after removing all the browser settings, so maybe I am still missing something. Anyway, it's a dead end and without some automatic tooling to convert to the old format it's a cumbersome process if you make frequent changes in your database. For now I switched to Keepass2Android. Works fine, but the current lack of clipboard exchange between the Android and Sailfish layer on my Xperia XA makes this far from ideal.

**Comment by jobe-m** [comment]
Keepass KDBX4 file format support is on the way thanks to @24mu13 :)
I need to sort out some things and will do a release after that. In the mean time there might be a pre-release for testing which I could put to openrepos. Stay tuned!

**Comment by jobe-m** [comment]
More info on this topic in #26 while we integrate the new keepassxc database support
