### ISSUE TITLE
Did not work with Sailfish OS3

### ISSUE THREAD

**Issue by playforvoices-marko** [jobe-m/ownkeepass#21]
Tried to install ownkeepass on a Xperia X (Single SIM) with SailfishOS3. The openrepos store gives me a error message. 
![bildschirmfoto_20181101_001](https://user-images.githubusercontent.com/41583370/47855550-30c0ef80-dde5-11e8-8705-395929f658e8.png)

**Comment by jobe-m** [comment]
Sorry, cannot help. I do not have a device with sfos 3

**Comment by direc85** [comment]
I just installed ownKeepass using SFOS 3.0.0.8, so I guess it was a temporary issue. Fixed for me.

**Comment by jobe-m** [comment]
Thanks for reporting.
