### ISSUE TITLE
Unlocking the password safe by entering the first 3 characters does not work

### ISSUE THREAD

**Issue by pietsch** [jobe-m/ownkeepass#24]
I am using ownKeePass version 1.2.4 from the official Jolla store with a version 2 database I created with KeePassX 2.0.3 on a Linux laptop.

This database opens just fine with the password and key file I transferred to my up-to-date Sailfish X phone. However, the very convenient feature (in German:) “Entsperre deinen Passwort-Safe durch Eingabe der ersten 3 Zeichen des Zugangspasswortes” or (translated into English:) “Unlock your password safe by entering the first 3 characters of your access password” always fails. In my case, these contain special characters, however they are all from the US-ASCII character set.

**Comment by jobe-m** [comment]
Can you please let me know which of the special characters actually cause problems?
I have tested it with a few characters but could not reproduce...

**Comment by pietsch** [comment]
Sorry, too long ago – I forget. In the meantime, my Sailfish device was stolen.

**Comment by jobe-m** [comment]
Sorry to hear
