### ISSUE TITLE
Option to forget the previously used database

### ISSUE THREAD

**Issue by lausvi** [jobe-m/ownkeepass#27]
Hi.
For one time, I tested using a database with a key file. Since then the app keeps suggesting that configuration for me everytime when I launch the app. Now to use my currently used, non-key-filed database I need to 'Open database', browse for the database file, and open it. Next time I launch the app, it again suggests the key-filed configuration. 

Where does the app keep that 'last used' configuration so I could delete it manually?

I am using version 1.2.4. I tried removing the app but it still keeps the config.

Other than that, thanks a million for the app, love it!

**Comment by jobe-m** [comment]
It is currently only possible to drop a database from the "Recent databases" list on the main page of ownKeepass. Not the currently used database.

But in your case you can adjust/delete the path to the key file in the settings which you find on the device in /home/nemo/.config/harbour-ownkeepass/settings.ini.
The line of interest is:

    recentDatabases\1\keyFilePath=

(just make it empty)

What you can also do is to create another dummy Keepass database. Then when you reopen ownKeepass the database with keyfile is moved to the "recent Database" list. There with a long-tab you can select "Drop from list". Now you can reopen your original database without keyfile and it should be saved as last opened database. The dummy database you can remove as described also. (And delete the file from the filesystem.)
