### ISSUE TITLE
Usability request : file opening paths and their persistence

### ISSUE THREAD

**Issue by canne** [jobe-m/ownkeepass#30]
With 0.9.5 some of the database opening related functions have gone towards a bit confusing direction for a lambda user, I presume.. I would like to propose to check  at least:
- [ ] Persistence of the recent DB list when application relaunched (known issue in 0.9.5)
- [ ] Persistence of the database paths in Open dialogue (is this a known issue or a planned feature ?)
- [x] Is the password field empty by default ?
- [ ] Is a check done for the existence of the suggested 'ownkeepass' sub-folder in the proposed base directory ?
- [x] Can the database file be a symbolic link to Dropbox folder (Sailbox app.) ?

My suggestion:
<dl>
  <dt>Dummy user by default - no database </dt>
             <dd>Ask for a password/verify</dd>
             <dd>Create kdb-file in your default location (e.g. in /home/nemo/.config/harbour-ownkeepass)</dd>
   <dt>Returning dummy user</dt>
             <dd>Open the above created kdb-file by default from now own</dd>
   <dt>Advanced user by his/her own choice</dt>
      <dd>Current behaviour is good</dd>
      <dd>With persistent file paths in dialogue</dd>
      <dd>No need to create directories automatically</dd>
      <dd>Just provide a comprehensive warnings of missing files/directories</dd>
</dl>
In both cases, the recently opened databases suggested on home page are quite useless, I mean, is it likely that people want to maintain several databases? I have but two and find them with bookmarks feature of KeepassX. Lambda-user does not even know what is a kdb-file ?

**Comment by jobe-m** [comment]
With the new file browser dialog the usability should increase now significantly. So closing this now.
