### ISSUE TITLE
Req: As a user I want to fast unlock a locked database with only 3 characters

### ISSUE THREAD

**Issue by jobe-m** [jobe-m/ownkeepass#62]
- [x] The user shall be able to lock the database while the state of the database is preserved. So that the user returns to the same page after unlocking the database.
- [x] The user shall be able to unlock the database by only typing in the last 3 characters of the password. The feature shall be called fast-unlock.
- [x] If the user fails to fast-unlock the locked database the database shall be closed. So the user needs to type in the whole master password to open the database again.
- [x] The fast-unlock feature shall be configurable (enable/disable completely) in the App settings.

**Comment by tangrit** [comment]
- ideally use a free selectable substring of the Masterpassword 
- the number of fails should be adjustable ( I prefer 1 (one) )

**Comment by jobe-m** [comment]
Selectable substring is a good idea. I will take it into account!
