### ISSUE TITLE
[BUG] Update fast unlock code when database password is changed

### ISSUE THREAD

**Issue by jobe-m** [jobe-m/ownkeepass#80]
When user changes the master password for the database the fast unlock code is still the old one.

**Comment by tangrit** [comment]
fast unlock works fine for me.
Thank you very much. This makes the program much more efficient for daily use.

In the Jolla store resides v1.0.24. Would you mind to update the store content ?

**Comment by jobe-m** [comment]
Yes, of course I will update the Jolla store version. Just wanted to get some feedback from openrepos users which I suppose are in general a little more experienced if hitting a serious bug ;)

**Comment by tangrit** [comment]
> Am 07.03.2015 um 11:55 schrieb Marko Koschak <notifications@github.com <mailto:notifications@github.com>>:
> 
> Yes, of course I will update the Jolla store version. Just wanted to get some feedback

Well, I asked because just saw there is a version 1.0.25 I didn’t know about.

sincerely
Kai
