### ISSUE TITLE
Req: Number of tries for FastUnlock isn't changeable

### ISSUE THREAD

**Issue by tangrit** [jobe-m/ownkeepass#81]
instead of use Bool for fastUnlock a numeric value could configure the number of tries for fastUnlock by the use of this value for __counter in LockPage.qml
'0' disables fastUnlock

**Comment by jobe-m** [comment]
Good point! I will update fast unlock feature before releasing 1.1.0 in jolla store.
Thanks for your feedback!

**Comment by jobe-m** [comment]
Implemented with 4abf221ee1f147bf848bb7977a1a232afa809ebe

**Comment by tangrit** [comment]
It works. There is only one small issue: the number count not the possible tries but the retries.
So setting it to 1 the user has 2 chances and 0 doesn't disable fastUnlock.

**Comment by jobe-m** [comment]
Yes, that's right. It counts the retries. I have implemented that this way because I didn't need to change the already implemented logic. In the settings dialog there is still the switch to disable this feature completely. Also then the retry slider disappears from the settings dialog.
