### ISSUE TITLE
Regression: File Browser Doesn't Allow SD Card Selection

### ISSUE THREAD

**Issue by prplmnky** [jobe-m/ownkeepass#87]
I'm using version 1.1.0.

The File Browser is a nifty function but it doesn't allow me to browse my external SD Card. There appears to be an "SD Card" shortcut but it is always disabled. 

Thanks!

**Comment by jobe-m** [comment]
I can reproduce the problem. Sorry I didn't test this earlier before releasing 1.1.0. I will look into this issue the next evenings;)

**Comment by prplmnky** [comment]
Nice
