### ISSUE TITLE
[BUG] creates a new default database even if there is already one there

### ISSUE THREAD

**Issue by m-kress** [jobe-m/ownkeepass#92]
Hi,

I don't know if this is really a problem as the "expert mode" is gone since 1.1.3:
Even if there is a working database configured by the user, the program always creates a new one in ~/Documents/ownkeepass/notes.kdb.

Erasing this manually in ~/.config/harbour-ownkeepass/settings.ini and setting "recentDatabases\size=1" leads to an empty database after entering the correct password. Although the password is correct and seems to be accepted to open the database, there are no entries, because it creates a new database "notes.kbd".

How can I achive, that another database with another file name in another location stayes the default database that gets opened immediatelly?

Would it be posibble to auto-focus the password text field after startup in case there is only one database?

**Comment by m-kress** [comment]
Edit: Now I solved this issue by creating a symlink ~/Documents/ownkeepass/notes.kbd linking to the real database file.
Renaming my database to "notes.kbd" would be a solution, but the I would be forced to change the name on the backup machine, too :-(

**Comment by jobe-m** [comment]
This sounds like a bug. I will try to reproduce that and come back to you.

**Comment by jobe-m** [comment]
I think I found the bug. On app start the default database (Documents/ownkeepass/notes.kdb) was always set because recent database list model was initalized too late. This is now fixed. I guess this should also explain what you experienced.

**Comment by jobe-m** [comment]
Fix is included in release 1.1.4 which is already available on openrepos and soon also in jolla store

**Comment by m-kress** [comment]
Yes, this fixed it. Wow, this was fast :-) Thank you!
