### ISSUE TITLE
Version for Ubuntu phone

### ISSUE THREAD

**Issue by mivoligo** [jobe-m/ownkeepass#98]
Hi,
It's not much of an issue, rather a question. Do you maybe plan to make a version which will work on Ubuntu phones?

**Comment by jobe-m** [comment]
Hi,

I have no plans to port the application to Ubutnu phone by myself. But the SW structure enables different UI's. So if anyone wants to port the app to Ubuntu phone I am willing to accept contributions in that direction. 

All sources in common folder should be usable on all platforms.
All files in Sailfish folder needs to be ported to a new (QML) platform.
During that process it might be possible to identify parts of the QML sources which can be moved into a "common QML" folder. That QML components can then be used by all platforms.

**Comment by mivoligo** [comment]
Thanks for the quick answer and clarification.

**Comment by jobe-m** [comment]
Closing this as I have no intention to work on an Ubuntu phone version of ownKeepass
